In [ ]:
%%sql
CREATE TABLE baza_serce AS
SELECT *
FROM 'Dane/heartdisease_random_db.csv';

In [ ]:
%%sql
CREATE TABLE baza_serce_2 AS
SELECT *
FROM 'Dane/healthcare_dataset_stroke_data.csv';

In [ ]:
%%sql
CREATE TABLE wszystko AS
SELECT * FROM baza_serce
UNION BY NAME
SELECT * FROM baza_serce_2;

In [15]:
%%sql
SELECT *
FROM wszystko
LIMIT 100;

,id,age,sex,chest_pain_type,resting_blood_presure,serum_cholesterol,fasting_blood_sugar,heart_disease_diagnosis,gender,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,3,58,Female,Atypical Angina,110.0,217.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10,51,Female,Asymptomatic,120.0,295.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,27,64,Female,Atypical Angina,130.0,303.0,1.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28,54,Male,Non-Anginal Pain,120.0,188.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,35,51,Female,Typical Angina,125.0,213.0,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,51314,78,NaN,NaN,NaN,NaN,NaN,NaN,Female,0.0,0.0,True,Private,Urban,106.74,33.0,formerly smoked,1.0
96,35578,78,NaN,NaN,NaN,NaN,NaN,NaN,Male,0.0,0.0,False,Self-employed,Urban,90.19,26.9,never smoked,1.0
97,39186,57,NaN,NaN,NaN,NaN,NaN,NaN,Female,0.0,1.0,True,Private,Urban,216.58,31.0,Unknown,1.0
98,31154,39,NaN,NaN,NaN,NaN,NaN,NaN,Female,0.0,0.0,True,Self-employed,Urban,97.76,29.6,smokes,1.0
99,25974,78,NaN,NaN,NaN,NaN,NaN,NaN,Male,0.0,0.0,True,Self-employed,Urban,218.46,26.8,Unknown,1.0

In [ ]:
%%sql
CREATE OR REPLACE TABLE joined_data_id AS
SELECT *
FROM  baza_serce
JOIN  baza_serce_2
USING (id);

In [11]:
%%sql
SELECT COUNT(*)
FROM baza_wszystko
GROUP BY gender;

   count_star()
0           501
1            26
2            13